// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

type User struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	EmailVerified bool
	PasswordHash  []byte
	CreatedAt     time.Time
}
