//go:build go1.22

// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// BookResponse defines model for BookResponse.
type BookResponse struct {
	// CreatedAt The timestamp when the book was created
	CreatedAt time.Time `json:"created_at"`

	// Id The unique identifier for the book
	Id openapi_types.UUID `json:"id"`

	// Name The name of the book
	Name string `json:"name"`

	// UpdatedAt The timestamp when the book was updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId The unique identifier for the book owner
	UserId openapi_types.UUID `json:"user_id"`
}

// CreateBookRequest defines model for CreateBookRequest.
type CreateBookRequest struct {
	// Name The name of the book
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Message A human-readable error message
	Message string `json:"message"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Field The name of the field that caused the validation error
	Field string `json:"field"`

	// Message The specific error message for the field
	Message string `json:"message"`
}

// ListBookResponse defines model for ListBookResponse.
type ListBookResponse struct {
	// Items A list of book
	Items    []BookResponse `json:"items"`
	Metadata Pagination     `json:"metadata"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email The email address of the user
	Email openapi_types.Email `json:"email"`

	// Password The password of the user
	Password string `json:"password"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// CurrentPage The current page number
	CurrentPage int `json:"current_page"`

	// FirstPage The first page
	FirstPage int `json:"first_page"`

	// LastPage The last page
	LastPage int `json:"last_page"`

	// PageSize The number of items per page
	PageSize int `json:"page_size"`

	// TotalItems The total number of items across all pages
	TotalItems int `json:"total_items"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	// Email The email address of the user
	Email openapi_types.Email `json:"email"`

	// FirstName The first name of the user
	FirstName string `json:"first_name"`

	// LastName The last name of the user
	LastName string `json:"last_name"`

	// Password The password of the user
	Password string `json:"password"`
}

// ResendCodeRequest defines model for ResendCodeRequest.
type ResendCodeRequest struct {
	// Email The email address to which the new verification code should be sent
	Email openapi_types.Email `json:"email"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	// RefreshToken The refresh token obtained during initial login or previous refresh
	RefreshToken string `json:"refresh_token"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken The access token used for accessing protected resources
	AccessToken string `json:"access_token"`

	// ExpiresIn The lifetime in seconds of the access token
	ExpiresIn int `json:"expires_in"`

	// RefreshToken The refresh token used to obtain new access token
	RefreshToken string `json:"refresh_token"`

	// TokenType The type of token issued
	TokenType string `json:"token_type"`
}

// UpdateBookRequest defines model for UpdateBookRequest.
type UpdateBookRequest struct {
	// Name The name of the book
	Name string `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// CreatedAt The timestamp when the user was created
	CreatedAt time.Time `json:"created_at"`

	// Email The email of the user
	Email openapi_types.Email `json:"email"`

	// EmailVerified Returns true if user email is verified or false if otherwise
	EmailVerified bool `json:"email_verified"`

	// FirstName The first name of the user
	FirstName string `json:"first_name"`

	// Id The unique identifier for the user
	Id openapi_types.UUID `json:"id"`

	// LastName The last name of the user
	LastName string `json:"last_name"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Errors A list of specific field validation errors
	Errors []FieldError `json:"errors"`

	// Message A human-readable summary of the overall error
	Message string `json:"message"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	// Email The email address to be verified
	Email openapi_types.Email `json:"email"`

	// VerificationCode The 6-digit verification code received by the email
	VerificationCode string `json:"verification_code"`
}

// ListBookHandlerParams defines parameters for ListBookHandler.
type ListBookHandlerParams struct {
	Name     *string `form:"name,omitempty" json:"name,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// LoginUserHandlerJSONRequestBody defines body for LoginUserHandler for application/json ContentType.
type LoginUserHandlerJSONRequestBody = LoginRequest

// RegisterUserHandlerJSONRequestBody defines body for RegisterUserHandler for application/json ContentType.
type RegisterUserHandlerJSONRequestBody = RegistrationRequest

// ResendCodeHandlerJSONRequestBody defines body for ResendCodeHandler for application/json ContentType.
type ResendCodeHandlerJSONRequestBody = ResendCodeRequest

// VerifyEmailHandlerJSONRequestBody defines body for VerifyEmailHandler for application/json ContentType.
type VerifyEmailHandlerJSONRequestBody = VerifyEmailRequest

// CreateBookHandlerJSONRequestBody defines body for CreateBookHandler for application/json ContentType.
type CreateBookHandlerJSONRequestBody = CreateBookRequest

// UpdateBookHandlerJSONRequestBody defines body for UpdateBookHandler for application/json ContentType.
type UpdateBookHandlerJSONRequestBody = UpdateBookRequest

// RefreshTokenHandlerJSONRequestBody defines body for RefreshTokenHandler for application/json ContentType.
type RefreshTokenHandlerJSONRequestBody = TokenRefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in a user
	// (POST /auth/login)
	LoginUserHandler(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/registration)
	RegisterUserHandler(w http.ResponseWriter, r *http.Request)
	// Resend email verification code
	// (POST /auth/resend-code)
	ResendCodeHandler(w http.ResponseWriter, r *http.Request)
	// Verify user email address
	// (POST /auth/verify-email)
	VerifyEmailHandler(w http.ResponseWriter, r *http.Request)
	// Retrieve all books that belongs to the user
	// (GET /books)
	ListBookHandler(w http.ResponseWriter, r *http.Request, params ListBookHandlerParams)
	// Create a new book
	// (POST /books)
	CreateBookHandler(w http.ResponseWriter, r *http.Request)
	// Delete a specific book that belongs to the user by ID
	// (DELETE /books/{id})
	DeleteBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a specific book that belongs to the user by ID
	// (GET /books/{id})
	GetBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a specific book that belongs to the user by ID
	// (PUT /books/{id})
	UpdateBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Refresh access token
	// (POST /token/refresh)
	RefreshTokenHandler(w http.ResponseWriter, r *http.Request)
	// Get user profile by ID
	// (GET /users/{id})
	GetUserHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUserHandler operation middleware
func (siw *ServerInterfaceWrapper) LoginUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUserHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterUserHandler operation middleware
func (siw *ServerInterfaceWrapper) RegisterUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUserHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResendCodeHandler operation middleware
func (siw *ServerInterfaceWrapper) ResendCodeHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendCodeHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VerifyEmailHandler operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmailHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmailHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListBookHandler operation middleware
func (siw *ServerInterfaceWrapper) ListBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookHandlerParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookHandler(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateBookHandler operation middleware
func (siw *ServerInterfaceWrapper) CreateBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBookHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteBookHandler operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetBookHandler operation middleware
func (siw *ServerInterfaceWrapper) GetBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateBookHandler operation middleware
func (siw *ServerInterfaceWrapper) UpdateBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RefreshTokenHandler operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokenHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokenHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserHandler operation middleware
func (siw *ServerInterfaceWrapper) GetUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.LoginUserHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/registration", wrapper.RegisterUserHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/resend-code", wrapper.ResendCodeHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/verify-email", wrapper.VerifyEmailHandler)
	m.HandleFunc("GET "+options.BaseURL+"/books", wrapper.ListBookHandler)
	m.HandleFunc("POST "+options.BaseURL+"/books", wrapper.CreateBookHandler)
	m.HandleFunc("DELETE "+options.BaseURL+"/books/{id}", wrapper.DeleteBookHandler)
	m.HandleFunc("GET "+options.BaseURL+"/books/{id}", wrapper.GetBookHandler)
	m.HandleFunc("PUT "+options.BaseURL+"/books/{id}", wrapper.UpdateBookHandler)
	m.HandleFunc("POST "+options.BaseURL+"/token/refresh", wrapper.RefreshTokenHandler)
	m.HandleFunc("GET "+options.BaseURL+"/users/{id}", wrapper.GetUserHandler)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe2/bthb/KoTugK2AYzvPtv7rtku6m2HrhrQdcNHmGrR0bLGVSJWknHqBv/sFDyVZ",
	"D8p2EjnN2vyXWNR58ZzfeZC69nwRJ4ID18obXXvKDyGm+OdLIT5dgEoEV2D+T6RIQGoG+NSXQDUEY6rN",
	"fwEoX7JEM8G9kfc2BKJZDErTOCFXIXCiQyATIT6RK6pI9q7X86ZCxoaCF1ANe+Ydr+fpRQLeyFNaMj7z",
	"lj2PBW4eKWefUyAsAK7ZlIEkUyELVl7Pgy80TiJD7HgIJwf7x8He5Ng/2Tt69vxk7/mzp/7e9HA4PTx5",
	"+mx6MnxWlidNWeAShdMY3MKYJ0RM3ewvzt68JTRhJADFZtxFOU2CWxs0e3drg6YK5Ph2ViXiioPcgW2X",
	"PU/C55RJCLzRew+XoLVX4vbKXlex2GVBTkw+gq+Nkj/jWuvFn1NQuunEu9rNmi7IxiXimZRCNsWKQSk6",
	"c0j2goRpTPmeBBrQSQQEDAGSry/LeM7nNGIBYTxJNUmkmLMANps9J+WS9hWDKGgReWqebTYlLiM6pJr4",
	"NFUQ4K8oKTWvWIUqikRU6XHmCA1HbrWUYawS8NmU+VUrFd5sRS6zilOlyQRubq1epr/Lar8xpddDKdMQ",
	"K9dmR0xpY7nMAYt1P0iYeiPvX4MVdg8y4B5UWC0LeaiUdGEtpmlANd1E5086Yxz3xKF1RiIXyam2mDHe",
	"GngQUxa5dw0fERoEEpTK/cYgQGWrPoqQBwL+nf3S90VchhhL3+EwCVXqSsgWV82f1tgWZIu3NzlGzr94",
	"wWWikomb6TWVErgeJ63ena0gZgXhaTypWmi/YMi4hhlIw3HKpFpHE58jxY2kMCzbKZnHTUIHLkpm1Vix",
	"v9uQGFUzO4LORhKQTcJDF2EtNI3GLdGFKdUsaDCgvhRKERpFyEeVGR0d97yYcRansTdyMK25QWUXK+Yv",
	"G7AqadkgLq+5gBlTWqLfPLz4siq251XrYeWU0GD9qwidBdIqEbR73FrCpwK+IiSULNOrJLWtsOICFPDg",
	"ZxHA3fdcC3IVMj9EfThckTlIkydtBvZFAESFIo0CkwsVcN2BZzjx0aXoW/EJ+AVMJaiwVVVpn4+1WexW",
	"OVtCcAkRE00Zh4AEqZGHMM40oxGJTJYiQpJEwpyJVOXvbdSgKsIaTdqyPvV9UGqdCnZFpgEWS6Z0sb8a",
	"JRIpNPgaAiJBiVT6iFUN/4YvCZOgxqyFTcSmYBoFwjhR4AseFLBQlqDsBIcnQyfi3nhfbAkosv1BZ6zx",
	"bKiDD8b2ZyeoLxILAciAKZVCtcp7CVRiDK/f4Mr+1FWriFExscsT3mGj8qA7kXcKZKfNvsHJWzX7G2Gs",
	"65SFD8YWA8GRBS5Ap5IroqXpiqdWMysKUyR/z4DIlEYKlwgdgrxiqlKkmPcL9hMhIqB8xynz5i1+g/RR",
	"R4OT3WRv19BgY6KtDBFqu++Kjb+K9rSl+cX+cm0HV7SitgGuN7xq2+6u1II7e7tt5wYqjWMqF7mxxRyk",
	"qXeb3Xc+RjD9XtEXo7fIUh16g0Y509dpZ7MJizOzIZ0UORMoorMToCiXSWNTJrnlONkL2IxpR1UlwQc2",
	"h4BMFmj2nNNKtP2D58OTYywGtQZpSP7vw4fg+mT5w9Y9Z1PMprGXPU+Bn0qmF2+Ma1nj2sz4ItVhU7Mz",
	"rkE2igJTM+AsBY1HfrQUyId0ODz0cQX+CT96PTtaRuyrJeBQ68RbGpkYnwq3UTHRvfjzvIgka1bjiCYp",
	"YuHDtM3v5v/iBWsQZSnt94f9odlKkQCnCfNG3mF/2D+0Bg/RCAOa6nCAhSG6n7BuaJwQeZ4H3shON0zO",
	"/A/lQYTKSOuyL0WwwJQpuDals6n0kiTKBB58VLbbtwG9KdwrQ5RldcNNOsEfbNJG2Q+Gw854V8tXZF7d",
	"FqO+KaBnEGDpmKJfTNMoQjA66lCWDPGaMrRMOZH9/u7Zv+PGWYRkf2dMDw46Y1rPOg72ryiLoJxNjAzH",
	"92N3g040Igrk3JRD2cKel2UWGyPGL2ieyjWdKYNTiC+XZq0NtUoiaY04O/YAufugcw1Ytoq97hyuUo23",
	"hZ7MLAJBNfZ6Xgg0AFuQ/Cb8wrBNVH13cZ6XAByuokVerOdbtpJ2laIG5pka3LgulMyRwZYPASie3wNQ",
	"YDfEdEh0yFReqkSmHlsQ+MKUVo/4UcOPPOIJxbnARhRRwIO9vCxrA5F8irZrCKlP63aQvFvPDFex+qJl",
	"vBdSRSYAHKd7plReiFSS7UZ37SeEzW3+qzlYLCEVwT3TD6JYONqCfWHXkrVLkW2D2tFcEC40mYqUI6/O",
	"kKToxizjCpPtQM2p0Fmljcoxqmik7q7BWQX8VoRrwW8iKFOt4cBrcADXLvaKPtENBKVWc7dI4Ohpvw4U",
	"nJUsWasY+uS/Jvyp74uUa8IU4eKKUF+zOfSdeLAx8C23SrDnrPvkhYvRvaNAttvkJ+jPSEwjU6lABg5P",
	"/rGgYEq5bw0Yvn5dZJ0EE5ixZjbhUU9qoGWDvTwgzqzlxis7uBhdezNwjRiyeyMrfEqopDForOzfX3vM",
	"iPo5BbnIb0qN8gtTK0tsPk8w6V8BlX5IpsJ5LOJmlR1dr2NVuppguEjQksEcyFTixK04SN93HaS3c7Vn",
	"4+tZx/SLod043C+LUbpJsFaUyx1OWRq3gxzu+KZaM1npA7yggC5k71NNIBJ8hhoW8/Ot5yBuFCtNN0YG",
	"tVdjv5jZI0ghCbN42gWKlfjZiHstMn4FpAlZHOzlnAf29C14UhlrYoiUB5rvL81GliuMzA22sOMqfHG4",
	"6F0uey2FxerS4W7riublxnseUWxyWvO8GCd0Pp/IDkKd8wncy8HxPc8nnBFUqzVGpTrDvEcmxiXuHjjO",
	"kub3gtWvb/54jayefHeA8BBGKjcBJRvW2cQjc/I69BSlw+CaBUsbOBFoaILRKf6+uYhIqA5XKRYPUatA",
	"sj7X3vs1/Dtn5C36JcQva9gGfnU3IGnn8h1G6vDwtuq+EnLCggD4iCxESkI6N4W6KfBQW8FNNs/PLUOm",
	"igtTHahe8C70bmELBdcbVio2jAld3SKwdXtLtUImC3J+6qxZnI3GL6AfIaL72kc5q/bHuP624/pOYyP0",
	"GxzjnJ+SbeKg0yESci8RvAlE/QK6C3xKUgc+rW5PfosQ1X1r2Lxtes83R7aCx+zjvVteG3nsth6x/hHr",
	"u8P6bfvkkiqrS6/Zt5/58HmlY+N7yvId1TXHsQ+lG7dIevfEZjp2DJtB/nXJmhsKuAAv3+12guj60Oah",
	"XTF8XfsehPxEeUAEPqa2ri59TfIk/9qj4zRS+fSDIPJkFtpVMsngvapdp+nkovIZzgrNDcJngL6TlNLg",
	"Wx3el6bzdl39a6DmKZq9jpaPwto63Oq1wVr52FoMnp+WP0coHx7d5huJm1epX7PJ3eoOYiLFlEVQOpX6",
	"7odYHVwaOD8lR/ddESD3O3R/adkd6onQEP+dcjqD2FjlcmnJy7k7Ak9hDpFIzNrsgqDX81IZZd8KjAaD",
	"/YOn/WF/2N8fHQ2Hw8F83zMSZeyu22/LWlDoZd99mmSS+dNKuCI2Uddlr07tjxxaTB6IsIfRovgIIXvX",
	"Zv5tXy7brkSkZrXl5fL/AQAA//9GsJ9GrkcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
