//go:build go1.22

// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// BookResponse defines model for BookResponse.
type BookResponse struct {
	// CreatedAt The timestamp when the book was created
	CreatedAt time.Time `json:"created_at"`

	// Id The unique identifier for the book
	Id openapi_types.UUID `json:"id"`

	// Name The name of the book
	Name string `json:"name"`

	// UpdatedAt The timestamp when the book was updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId The unique identifier for the book owner
	UserId openapi_types.UUID `json:"user_id"`
}

// CreateBookRequest defines model for CreateBookRequest.
type CreateBookRequest struct {
	// Name The name of the book
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Message A human-readable error message
	Message string `json:"message"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Field The name of the field that caused the validation error
	Field string `json:"field"`

	// Message The specific error message for the field
	Message string `json:"message"`
}

// ListBookResponse defines model for ListBookResponse.
type ListBookResponse struct {
	// Items A list of book
	Items    *[]BookResponse `json:"items,omitempty"`
	Metadata *Pagination     `json:"metadata,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email The email address of the user
	Email openapi_types.Email `json:"email"`

	// Password The password of the user
	Password string `json:"password"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// CurrentPage The current page number
	CurrentPage int `json:"current_page"`

	// PageSize The number of items per page
	PageSize int `json:"page_size"`

	// TotalItems The total number of items across all pages
	TotalItems int `json:"total_items"`

	// TotalPages The total number of pages
	TotalPages int `json:"total_pages"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	// Email The email address of the user
	Email openapi_types.Email `json:"email"`

	// FirstName The first name of the user
	FirstName string `json:"first_name"`

	// LastName The last name of the user
	LastName string `json:"last_name"`

	// Password The password of the user
	Password string `json:"password"`
}

// ResendCodeRequest defines model for ResendCodeRequest.
type ResendCodeRequest struct {
	// Email The email address to which the new verification code should be sent
	Email openapi_types.Email `json:"email"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	// RefreshToken The refresh token obtained during initial login or previous refresh
	RefreshToken string `json:"refresh_token"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken The access token used for accessing protected resources
	AccessToken string `json:"access_token"`

	// ExpiresIn The lifetime in seconds of the access token
	ExpiresIn int `json:"expires_in"`

	// RefreshToken The refresh token used to obtain new access token
	RefreshToken string `json:"refresh_token"`

	// TokenType The type of token issued
	TokenType string `json:"token_type"`
}

// UpdateBookRequest defines model for UpdateBookRequest.
type UpdateBookRequest struct {
	// Name The name of the book
	Name string `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// CreatedAt The timestamp when the user was created
	CreatedAt time.Time `json:"created_at"`

	// Email The email of the user
	Email openapi_types.Email `json:"email"`

	// EmailVerified Returns true if user email is verified or false if otherwise
	EmailVerified bool `json:"email_verified"`

	// FirstName The first name of the user
	FirstName string `json:"first_name"`

	// Id The unique identifier for the user
	Id openapi_types.UUID `json:"id"`

	// LastName The last name of the user
	LastName string `json:"last_name"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Errors A list of specific field validation errors
	Errors []FieldError `json:"errors"`

	// Message A human-readable summary of the overall error
	Message string `json:"message"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	// Email The email address to be verified
	Email openapi_types.Email `json:"email"`

	// VerificationCode The 6-digit verification code received by the email
	VerificationCode string `json:"verification_code"`
}

// ListBookHandlerParams defines parameters for ListBookHandler.
type ListBookHandlerParams struct {
	Name     *string `form:"name,omitempty" json:"name,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// LoginUserHandlerJSONRequestBody defines body for LoginUserHandler for application/json ContentType.
type LoginUserHandlerJSONRequestBody = LoginRequest

// RegisterUserHandlerJSONRequestBody defines body for RegisterUserHandler for application/json ContentType.
type RegisterUserHandlerJSONRequestBody = RegistrationRequest

// ResendCodeHandlerJSONRequestBody defines body for ResendCodeHandler for application/json ContentType.
type ResendCodeHandlerJSONRequestBody = ResendCodeRequest

// VerifyEmailHandlerJSONRequestBody defines body for VerifyEmailHandler for application/json ContentType.
type VerifyEmailHandlerJSONRequestBody = VerifyEmailRequest

// CreateBookHandlerJSONRequestBody defines body for CreateBookHandler for application/json ContentType.
type CreateBookHandlerJSONRequestBody = CreateBookRequest

// UpdateBookHandlerJSONRequestBody defines body for UpdateBookHandler for application/json ContentType.
type UpdateBookHandlerJSONRequestBody = UpdateBookRequest

// RefreshTokenHandlerJSONRequestBody defines body for RefreshTokenHandler for application/json ContentType.
type RefreshTokenHandlerJSONRequestBody = TokenRefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in a user
	// (POST /auth/login)
	LoginUserHandler(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/registration)
	RegisterUserHandler(w http.ResponseWriter, r *http.Request)
	// Resend email verification code
	// (POST /auth/resend-code)
	ResendCodeHandler(w http.ResponseWriter, r *http.Request)
	// Verify user email address
	// (POST /auth/verify-email)
	VerifyEmailHandler(w http.ResponseWriter, r *http.Request)
	// Retrieve all books that belongs to the user
	// (GET /books)
	ListBookHandler(w http.ResponseWriter, r *http.Request, params ListBookHandlerParams)
	// Create a new book
	// (POST /books)
	CreateBookHandler(w http.ResponseWriter, r *http.Request)
	// Delete a specific book that belongs to the user by ID
	// (DELETE /books/{id})
	DeleteBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a specific book that belongs to the user by ID
	// (GET /books/{id})
	GetBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a specific book that belongs to the user by ID
	// (PUT /books/{id})
	UpdateBookHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Refresh access token
	// (POST /token/refresh)
	RefreshTokenHandler(w http.ResponseWriter, r *http.Request)
	// Get user profile by ID
	// (GET /users/{id})
	GetUserHandler(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUserHandler operation middleware
func (siw *ServerInterfaceWrapper) LoginUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUserHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterUserHandler operation middleware
func (siw *ServerInterfaceWrapper) RegisterUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUserHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResendCodeHandler operation middleware
func (siw *ServerInterfaceWrapper) ResendCodeHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendCodeHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VerifyEmailHandler operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmailHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmailHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListBookHandler operation middleware
func (siw *ServerInterfaceWrapper) ListBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookHandlerParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookHandler(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateBookHandler operation middleware
func (siw *ServerInterfaceWrapper) CreateBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBookHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteBookHandler operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetBookHandler operation middleware
func (siw *ServerInterfaceWrapper) GetBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateBookHandler operation middleware
func (siw *ServerInterfaceWrapper) UpdateBookHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBookHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RefreshTokenHandler operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokenHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokenHandler(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserHandler operation middleware
func (siw *ServerInterfaceWrapper) GetUserHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserHandler(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.LoginUserHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/registration", wrapper.RegisterUserHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/resend-code", wrapper.ResendCodeHandler)
	m.HandleFunc("POST "+options.BaseURL+"/auth/verify-email", wrapper.VerifyEmailHandler)
	m.HandleFunc("GET "+options.BaseURL+"/books", wrapper.ListBookHandler)
	m.HandleFunc("POST "+options.BaseURL+"/books", wrapper.CreateBookHandler)
	m.HandleFunc("DELETE "+options.BaseURL+"/books/{id}", wrapper.DeleteBookHandler)
	m.HandleFunc("GET "+options.BaseURL+"/books/{id}", wrapper.GetBookHandler)
	m.HandleFunc("PUT "+options.BaseURL+"/books/{id}", wrapper.UpdateBookHandler)
	m.HandleFunc("POST "+options.BaseURL+"/token/refresh", wrapper.RefreshTokenHandler)
	m.HandleFunc("GET "+options.BaseURL+"/users/{id}", wrapper.GetUserHandler)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe2/bthb/KoTugK2AYzvPtv7rtku6m2HrhrQdcNHmGrR0bLGVSJWknHqBv/sFDyVZ",
	"D8p2EjnN2vyXWCTPg+f8zoPkteeLOBEcuFbe6NpTfggxxT9fCvHpAlQiuALzfyJFAlIzwK++BKohGFNt",
	"/gtA+ZIlmgnujby3IRDNYlCaxgm5CoETHQKZCPGJXFFFsrlez5sKGZsVvIBq2DNzvJ6nFwl4I09pyfjM",
	"W/Y8FrhppJx9ToGwALhmUwaSTIUsSHk9D77QOInMYsdDODnYPw72Jsf+yd7Rs+cne8+fPfX3pofD6eHJ",
	"02fTk+GzMj9pygIXK5zG4GbGfCFi6iZ/cfbmLaEJIwEoNuOuldMkuLVCs7lbKzRVIMe30yoRVxzkDnS7",
	"7HkSPqdMQuCN3ns4BLW9YrdXtrqKxi6L5cTkI/jaCPkzjrVW/DkFpZtGvKvdrMmCZFwsnkkpZJOtGJSi",
	"MwdnL0iYxpTvSaABnURAwCxA8vFlHs/5nEYsIIwnqSaJFHMWwGa150u5uH3FIApaWJ6ab5tVicOIDqkm",
	"Pk0VBPgrckrNFCtQRZCIKj3ODKFhyK2aMoRVAj6bMr+qpcKaLctlUnGqNJnAzbXVy+R3ae03pvR6KGUa",
	"YuXa7IgpbTSXGWAx7gcJU2/k/Wuwwu5BBtyDCqllwQ+Vki6sxjQNqKab1vmTzhjHPUGpm2KJGeOtjgUx",
	"ZZF7V/AToUEgQancLoyHV7biowh5IODf2S99X8RlCLHrOwwioUpdCdliivnXGtli2WL2po3P6RcTXDtf",
	"UmEzfKZSAtfjpNV6sxHEjCA8jSdVDe33vJhxFqcx/p0RZ1zDDKTVxAzGiv3dBnC4olEEmhVJQCKpCo3h",
	"JiJaaBqNWwwYo5YZ0CBGfSmUIjSKkKYqEz06LhEdthO1E7ci2qCxSbDablc2q0q/qoKy1l0WcQEzprRE",
	"m3h4vjNlModaJ3X8XoHzBulfRehMblYg7lzZfF6/8KmAr+juJc30KgFpKxy4AAU8+FkEcPc914JchcwP",
	"UR4OV2QO0sQ4Gz19EQBRoUijwMQxBVx3YBlO7HMJ+lZ8An4BUwkqbBVV2u9jbQa7Rc6GEBxCxERTxiEg",
	"QWr4IYwzzWhEIhOBiJAkkTBnIlX5vI0SVFlYI0lbxKa+D0qtE8GOyCTARMekHfZXI0QihQZfQ0AkKJFK",
	"32JJ3b7hS8IkqDFrIROxKZgknzBOFPiCBwUslDkoG8HhydCJqjfeF5u+iWx/0BhrNBvi4Iex/dkJ3IvE",
	"QgASYEqlUM3QXgKV6MPrN7iyP3XRKmxUVOyyhHdYZDzoKuKdAtlpoW5w8laF+kYY6zpk4YexxUBwRIEL",
	"0KnkimhpKtqplcyywhTJ5xkQmdJI4RChQ5BXTFUyITO/ID8RIgLKdxwyb16eN5Y+6qjpsZvo7Sr4Nwba",
	"SgOgtvsu3/irKC1bClesDddWX0UZaYvXerGqtq3MSuWzsy7btuZXaRxTuciVLeYgTSLdrJzzFoAp94qa",
	"Fq1FlvLQGxS5mbxOPZtNWJyZDekkyZlA4Z2dAEU5TRqbNMnNx8lewGZMO7IqCT6wOQRkskC155RWrO0f",
	"PB+eHGMyqDVIs+T/PnwIrk+WP2xdTzbZbCp72fMU+KlkevHGmJZVro2ML1IdNiU74xpkIykwOQP2QVB5",
	"5Ee7AvmQDoeHPo7AP+FHr2fbwoh9tQAcap14S8MT41PhVioGuhd/nheeZNVqDNEERUx8mLbx3fxfTLAK",
	"UXal/f6wPzRbKRLgNGHeyDvsD/uHVuEhKmFAUx0OMDFE8xPWDI0RIs3zwBvZzoWJmf+hPIhQGGlN9qUI",
	"FhgyBdcmdTaZXpJEGcODj8pW8tahN7l7pUGyrG64CSf4gw3ayPvBcNgZ7Wr6isSr22LENwn0DAJMHVO0",
	"i2kaRQhGRx3ykiFek4eWDiWS3989+XfcGIuQ7O+M6MFBZ0TrUcdB/hVlEZSjieHh+H70btCJRkSBnJt0",
	"KBvY87LIYn3E2AXNQ7mmM2VwCvHl0oy1rlYJJK0eZ9seIHfvdK4Gy1a+153BVbLxNteTmUYgqPpezwuB",
	"BmATkt+EXyi2iarvLs7zFIDDVbTIk/V8y1bcrkLUwHxTgxvnhZI5ItjyIQDF83sACqyGmA6JDpnKU5XI",
	"5GMLAl+Y0uoRP2r4kXs8odgX2IgiCniwl6dlbSCSd9F2DSH1bt0Ognfred/KV1+0tPdCqsgEgGN3z6TK",
	"C5FKsl3rrv10r7nNfzUbiyWkIrhn+kEkC0dbkC/0WtJ2ybOtUzuKC8KFJlORcqTVGZIU1ZglXCGyHag5",
	"BTqrlFE5RhWF1N0lOKuA32rhmvMbD8pEaxjwGhzAsYu9ok50A0Gp1NwtEjhq2q8DBWclTdYyhj75r3F/",
	"6vsi5ZowRbi4ItTXbA59Jx5sdHxLreLsOek+eeEidO8okO02+Qn6MxLTyGQqkIHDk38sKJhU7lsDhq+f",
	"F1kjwQBmtJl1eNSTGmhZZy83iDNtufHKNi5G194MXC2G7M7HCp8SKmkMGjP799ceM6x+TkEu8ltOo/yy",
	"00oTm88TTPhXQKUfkqlwHou4SWUH2etIla4dGCoStGQwBzKV2HFbf3reTtWeja8nHdMvZu3GrYEyG6Xr",
	"CmtZudxhl6Vxs8dhjm+qOZPlPsCbD2hC9i7UBCLBZyhh0T/fug/iRrFSd2NkUHvV9ouZPYIUkjCLp12g",
	"WIme9bjXIqNXQJqQxcFeTnlgT9+CJ5W2JrpIuaH5/tJsZDnDyMxgCz2u3Bebi97lsteSWKwuDO42r2he",
	"TLznFsUmozXfi3ZC5/2J7CDU2Z/AvRwc33N/wulBtVxjVMozzDwyMSZxd8dxpjS/F6R+ffPHayT15LsD",
	"hIfQUrkJKFm3zjoemZHXoadIHQbXLFhax4lAQxOMTvH3zUlEQnW4CrF4iFoFkvWx9t6v0N85Im9RLyF+",
	"WcU28Ku7Bkk7le/QU4eHtxX3lZATFgTAR2QhUhLSuUnUTYKH0gpuonl+bhkyVVyY6kD0gnYhdwtZKKje",
	"MFOxbkzo6haBzdtbshUyWZDzU2fO4iw0fgH9CBHd5z7KmbU/+vW37dd3ahuh3WAb5/yUbOMHnTaRkHpp",
	"wZtA1C+gu8CnJHXg0+r25LcIUd2Xhs3bpvd8c2QreMwe3t3y2shjtfWI9Y9Y3x3Wb1snl0RZXXrN3m3m",
	"zeeVjI23kOU7qmuOYx9KNW6R9O6BzVTs6DaD/HXJmhsKOAAv3+22g+h6aPPQrhi+rr0HIT9RHhCBn6nN",
	"q0uvSZ7krz06DiOVpx8EkSfT0K6CSQbvVek6DScXlWc4KzQ3CJ8B+k5CSoNutXlf6s7bcfXXQM1TNHsd",
	"LW+FtVW41WuDtfSxNRk8Py0/RygfHt3mjcTNs9SvWeRudQcxkWLKIiidSn33TawOLg2cn5Kj+84IkPod",
	"qr+0bA71QGgW/51yOoPYaOVyaZeXc7cHnsIcIpGYsdkFQa/npTLK3gqMBoP9g6f9YX/Y3x8dDYfDwXzf",
	"Mxxl5K7bb8taUOhl7z5NMMnsacVc4Zso67JXX+2PHFpMHIiwhtGieISQzbWRf9vJZd2VFqlpbXm5/H8A",
	"AAD//2tzXHlqRwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
